let questions=[];
const $=id=>document.getElementById(id);
function status(id,msg,ok=false){$(id).textContent=msg;$(id).className='status '+(ok?'ok':'');}
function parseJSON(text){const clean=text.replace(/^\uFEFF/,'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const x=JSON.parse(clean);const arr=Array.isArray(x)?x:x.questions;if(!Array.isArray(arr))throw new Error('JSON में questions array नहीं मिला.');return arr.map((q,i)=>{if(!q.question||!Array.isArray(q.options))throw new Error('Question '+(i+1)+' invalid.');return {...q,correctOption:Number(q.correctOption)}})}
async function api(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function refresh(){const r=await fetch('/api/status');const j=await r.json();if(j.state==='logged_in')status('loginStatus','✅ Logged in'+(j.user?.username?' @'+j.user.username:''),true);else status('loginStatus','Status: '+j.state+(j.error?'\n'+j.error:''));}
$('sendCode').onclick=async()=>{try{status('loginStatus','Sending code...');const j=await api('/api/login/start',{apiId:$('apiId').value,apiHash:$('apiHash').value,phone:$('phone').value});$('codeBox').classList.remove('hidden');status('loginStatus','✅ Code sent. Telegram app/SMS में आया code डालें.',true)}catch(e){status('loginStatus','❌ '+e.message)}};
$('verify').onclick=async()=>{try{const j=await api('/api/login/verify',{code:$('code').value,password:$('password').value});status('loginStatus','✅ Login successful'+(j.user?.username?' @'+j.user.username:''),true)}catch(e){status('loginStatus','❌ '+e.message)}};
$('checkGroup').onclick=async()=>{try{const j=await api('/api/check-group',{groupId:$('groupId').value});status('groupStatus','✅ '+j.title+'\nID: '+j.id,true)}catch(e){status('groupStatus','❌ '+e.message)}};
$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;questions=parseJSON(await f.text());$('preview').textContent=JSON.stringify(questions.slice(0,8),null,2)+(questions.length>8?'\n...':''),status('summary','✅ '+questions.length+' questions loaded',true)}catch(err){questions=[];status('summary','❌ '+err.message)}};
$('loadSample').onclick=async()=>{try{const r=await fetch('/sample-questions.json');questions=parseJSON(await r.text());$('preview').textContent=JSON.stringify(questions,null,2);status('summary','✅ Sample: '+questions.length+' questions',true)}catch(e){status('summary','❌ '+e.message)}};
$('sendTest').onclick=async()=>{try{if(!questions.length)throw new Error('पहले JSON load करें.');const j=await api('/api/test',{groupId:$('groupId').value,question:questions[0]});status('publishStatus','✅ Test quiz sent. Message ID: '+j.messageId,true)}catch(e){status('publishStatus','❌ '+e.message)}};
$('publish').onclick=async()=>{try{if(!questions.length)throw new Error('पहले JSON load करें.');if(!confirm(questions.length+' quizzes भेजें?'))return;status('publishStatus','Publishing...');const j=await api('/api/publish',{groupId:$('groupId').value,questions,delayMs:Number($('delay').value)});status('publishStatus','✅ Published '+j.sent+'/'+j.total,true)}catch(e){status('publishStatus','❌ '+e.message)}};
$('logout').onclick=async()=>{await api('/api/logout',{});refresh()};
refresh();
